<?xml version="1.0" encoding="UTF-8" ?>
<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
        <OutputType>WinExe</OutputType>

        <!-- WinUI 3 -->
        <UseWinUI>true</UseWinUI>
        <EnableMsixTooling>true</EnableMsixTooling>
        <WindowsPackageType>None</WindowsPackageType>

        <!-- .NET MAUI -->
        <UseMaui>true</UseMaui>
        <MauiEnablePlatformUsings>true</MauiEnablePlatformUsings>

        <!-- Project Options -->
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>FocusScribe</RootNamespace>
        <EnableDefaultCssItems>false</EnableDefaultCssItems>
        <EnableDefaultXamlItems>false</EnableDefaultXamlItems>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- Target Platform Options -->
        <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>

        <!-- Minimum Target OS Version for Windows Platform -->
        <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>

        <!-- App Options -->
        <UseRidGraph>true</UseRidGraph>
        <Platforms>x86;x64;arm64</Platforms>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <PublishProfile>win-$(Platform).pubxml</PublishProfile>
        <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">win-x86;win-x64;win-arm64</RuntimeIdentifiers>
        <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="FocusScribe.code-workspace" />
        <None Remove="Directory.Packages.props" />
        <None Remove="FocusScribe.slnx" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="H.NotifyIcon.WinUI" Version="2.4.1" />
        <PackageReference Include="Microsoft.WindowsAppSDK" Version="[1.8.*,1.9)" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.*" />
        <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.*" />
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.*" Condition="'$(Configuration)' == 'Debug'" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="$(MauiVersion)" />
        <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
        <PackageReference Include="NAudio" Version="2.2.1" />

        <Manifest Include="$(ApplicationManifest)" />
    </ItemGroup>

    <!-- 
        Defining the "Msix" ProjectCapability here allows the Single-project MSIX Packaging
        Tools extension to be activated for this project even if the Windows App SDK Nuget
        package has not yet been restored.
    -->
    <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
        <ProjectCapability Include="Msix" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot\index.html">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <!-- 
        Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution 
        Explorer "Package and Publish" context menu entry to be enabled for this project even if 
        the Windows App SDK Nuget package has not yet been restored.
    -->
    <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
        <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
    </PropertyGroup>
</Project>
